/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StartIndexRouteImport } from './routes/start/index'
import { Route as StartSkillRouteImport } from './routes/start/skill'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiWebhooksGithubRouteImport } from './routes/api/webhooks/github'
import { Route as ApiAuthGithubCallbackRouteImport } from './routes/api/auth/github/callback'
import { Route as ApiAuthGithubLoginRouteImport } from './routes/api/auth/github/login'
import { Route as ReposOwnerRepoIndexRouteImport } from './routes/repos/$owner/$repo/index'
import { Route as ReposOwnerRepoPlanSplatRouteImport } from './routes/repos/$owner/$repo/plan/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartIndexRoute = StartIndexRouteImport.update({
  id: '/start/',
  path: '/start/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartSkillRoute = StartSkillRouteImport.update({
  id: '/start/skill',
  path: '/start/skill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksGithubRoute = ApiWebhooksGithubRouteImport.update({
  id: '/api/webhooks/github',
  path: '/api/webhooks/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubCallbackRoute = ApiAuthGithubCallbackRouteImport.update({
  id: '/api/auth/github/callback',
  path: '/api/auth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubLoginRoute = ApiAuthGithubLoginRouteImport.update({
  id: '/api/auth/github/login',
  path: '/api/auth/github/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposOwnerRepoIndexRoute = ReposOwnerRepoIndexRouteImport.update({
  id: '/repos/$owner/$repo/',
  path: '/repos/$owner/$repo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposOwnerRepoPlanSplatRoute = ReposOwnerRepoPlanSplatRouteImport.update({
  id: '/repos/$owner/$repo/plan/$',
  path: '/repos/$owner/$repo/plan/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/start/skill': typeof StartSkillRoute
  '/start/': typeof StartIndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/auth/github/login': typeof ApiAuthGithubLoginRoute
  '/repos/$owner/$repo/': typeof ReposOwnerRepoIndexRoute
  '/repos/$owner/$repo/plan/$': typeof ReposOwnerRepoPlanSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/start/skill': typeof StartSkillRoute
  '/start': typeof StartIndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/auth/github/login': typeof ApiAuthGithubLoginRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoIndexRoute
  '/repos/$owner/$repo/plan/$': typeof ReposOwnerRepoPlanSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/start/skill': typeof StartSkillRoute
  '/start/': typeof StartIndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/api/auth/github/callback': typeof ApiAuthGithubCallbackRoute
  '/api/auth/github/login': typeof ApiAuthGithubLoginRoute
  '/repos/$owner/$repo/': typeof ReposOwnerRepoIndexRoute
  '/repos/$owner/$repo/plan/$': typeof ReposOwnerRepoPlanSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/start/skill'
    | '/start/'
    | '/api/auth/logout'
    | '/api/webhooks/github'
    | '/api/auth/github/callback'
    | '/api/auth/github/login'
    | '/repos/$owner/$repo/'
    | '/repos/$owner/$repo/plan/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/start/skill'
    | '/start'
    | '/api/auth/logout'
    | '/api/webhooks/github'
    | '/api/auth/github/callback'
    | '/api/auth/github/login'
    | '/repos/$owner/$repo'
    | '/repos/$owner/$repo/plan/$'
  id:
    | '__root__'
    | '/'
    | '/start/skill'
    | '/start/'
    | '/api/auth/logout'
    | '/api/webhooks/github'
    | '/api/auth/github/callback'
    | '/api/auth/github/login'
    | '/repos/$owner/$repo/'
    | '/repos/$owner/$repo/plan/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StartSkillRoute: typeof StartSkillRoute
  StartIndexRoute: typeof StartIndexRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiWebhooksGithubRoute: typeof ApiWebhooksGithubRoute
  ApiAuthGithubCallbackRoute: typeof ApiAuthGithubCallbackRoute
  ApiAuthGithubLoginRoute: typeof ApiAuthGithubLoginRoute
  ReposOwnerRepoIndexRoute: typeof ReposOwnerRepoIndexRoute
  ReposOwnerRepoPlanSplatRoute: typeof ReposOwnerRepoPlanSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/': {
      id: '/start/'
      path: '/start'
      fullPath: '/start/'
      preLoaderRoute: typeof StartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/skill': {
      id: '/start/skill'
      path: '/start/skill'
      fullPath: '/start/skill'
      preLoaderRoute: typeof StartSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/github': {
      id: '/api/webhooks/github'
      path: '/api/webhooks/github'
      fullPath: '/api/webhooks/github'
      preLoaderRoute: typeof ApiWebhooksGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github/callback': {
      id: '/api/auth/github/callback'
      path: '/api/auth/github/callback'
      fullPath: '/api/auth/github/callback'
      preLoaderRoute: typeof ApiAuthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github/login': {
      id: '/api/auth/github/login'
      path: '/api/auth/github/login'
      fullPath: '/api/auth/github/login'
      preLoaderRoute: typeof ApiAuthGithubLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$owner/$repo/': {
      id: '/repos/$owner/$repo/'
      path: '/repos/$owner/$repo'
      fullPath: '/repos/$owner/$repo/'
      preLoaderRoute: typeof ReposOwnerRepoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$owner/$repo/plan/$': {
      id: '/repos/$owner/$repo/plan/$'
      path: '/repos/$owner/$repo/plan/$'
      fullPath: '/repos/$owner/$repo/plan/$'
      preLoaderRoute: typeof ReposOwnerRepoPlanSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StartSkillRoute: StartSkillRoute,
  StartIndexRoute: StartIndexRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiWebhooksGithubRoute: ApiWebhooksGithubRoute,
  ApiAuthGithubCallbackRoute: ApiAuthGithubCallbackRoute,
  ApiAuthGithubLoginRoute: ApiAuthGithubLoginRoute,
  ReposOwnerRepoIndexRoute: ReposOwnerRepoIndexRoute,
  ReposOwnerRepoPlanSplatRoute: ReposOwnerRepoPlanSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
